In [2]:
import pandas as pd 
import numpy as np 
import seaborn as sns
from rdkit import Chem

In [3]:
df=pd.read_csv("../data/co2_solubility_cleaned.csv")

In [126]:
df.sample(7)

,IL NAME,CATION NAME,ANION NAME,Cation_SMILES,Anion_SMILES,Temperature (0 C),Pressure (bar),CO2 capacity (mol CO2/mol IL),Cation_Family
1432,[BMPyr][NTf₂],1-butyl-1-methylpyrrolidinium,bis[(trifluoromethyl)sulfonyl]imide,CCCC[N+]1(CCCC1)C,FC(F)(F)S(=O)(=O)[N-]S(=O)(=O)C(F)(F)F,65.01,0.25,0.006036,Pyrrolidinium
5133,[N1888][NTf₂],methyltrioctylammonium,"1,1,1-trifluoro-N-[(trifluoromethyl)sulfonyl]m...",CCCCCCCC[N+](C)(CCCCCCCC)CCCCCCCC,FC(F)(F)S(=O)(=O)[N-]S(=O)(=O)C(F)(F)F,50.00,15.00,0.392758,Ammonium
600,[OMIM][TCM],1-methyl-3-octylimidazolium,tricyanomethanide,CCCCCCCC[n+]1ccn(C)c1,C([C-](C#N)C#N)#N,25.00,17.93,0.493206,Imidazolium
2066,[BMIM][MeSO₄],1-butyl-3-methylimidazolium,methyl sulfate,CCCC[n+]1ccn(C)c1,COS(=O)(=O)[O-],40.10,45.83,0.462047,Imidazolium
1255,[Pyr13][NTf₂],1-methyl-1-propylpyrrolidinium,bis[(trifluoromethyl)sulfonyl]imide,CCC[N+]1(CCCC1)C,FC(F)(F)S(=O)(=O)[N-]S(=O)(=O)C(F)(F)F,45.00,60.04,1.352941,Pyrrolidinium
2874,[P2228][Tf2N],triethyloctylphosphonium,bis(trifluoromethylsulfonyl)imide,CCCCCCCC[P+](CC)(CC)CC,FC(F)(F)S(=O)(=O)[N-]S(=O)(=O)C(F)(F)F,30.00,2.00,0.060445,Phosphonium
1394,[BMPyr][NTf₂],1-butyl-1-methylpyrrolidinium,bis[(trifluoromethyl)sulfonyl]imide,CCCC[N+]1(CCCC1)C,FC(F)(F)S(=O)(=O)[N-]S(=O)(=O)C(F)(F)F,45.00,10.00,0.215067,Pyrrolidinium

In [99]:
def family(name):
    name=str(name).lower()
    if 'imidazolium' in name:
        return "Imidazolium"
    if 'pyrrolidinium' in name:
        return "Pyrrolidinium"
    elif "pyridinium" in name:
        return "Pyridinium"
    elif "piperidinium" in name:
        return "Piperidinium"
    elif "phosphonium" in name:
        return "Phosphonium"
    elif "guanidinium" in name:
        return "Guanidinium"
    elif "sulfonium" in name:
        return "Sulfonium"
    elif "cyclopropenylium" in name:
        return "Cyclopropenylium"
    elif "ammonium" in name:
        return "Ammonium"
    elif "cholinium" in name:
        return "Ammonium"
    elif "aminium" in name:
        return "Ammonium"
    elif "triazabicyclo" in name:
        return "Amidinium"
    elif "hydrazinium" in name:
        return "Ammonium"
    elif "diamine" in name:
        return "Ammonium"
    elif "imidazol-3-ium" in name:
        return "Imidazolium"
    else:
        return "Others"

In [100]:
family("1-butyl-3-methylimidazolium")

'Imidazolium'

In [101]:
df["Cation_Family"]=df["CATION NAME"].apply(family)

In [102]:
df["Cation_Family"].value_counts()

Cation_Family
Imidazolium         3851
Ammonium             512
Pyrrolidinium        374
Phosphonium          272
Pyridinium           182
Guanidinium           42
Sulfonium             39
Cyclopropenylium      39
Piperidinium          36
Amidinium              2
Name: count, dtype: int64

In [108]:
len(df[df["Cation_Family"]=="Imidazolium"])

3851

In [113]:
name=df["Cation_Family"].unique()
table=pd.DataFrame(name,columns=["Cation"])
table["T(Kelvin)"] = ""
table["P(bar)"] = ""
table["xCO2"] = ""
table["Data Points"]=""
table

             Cation T(Kelvin) P(bar) xCO2 Data Points
0       Imidazolium
1          Ammonium
2       Phosphonium
3         Amidinium
4     Pyrrolidinium
5        Pyridinium
6         Sulfonium
7  Cyclopropenylium
8      Piperidinium
9       Guanidinium

In [120]:
for cation in df["Cation_Family"].unique():
    table.loc[table["Cation"]==cation,"Data Points"]=str(len(df[df["Cation_Family"]==cation]))
    t_max=df[df["Cation_Family"]==cation]["Temperature (0 C)"].max()
    t_min=df[df["Cation_Family"]==cation]["Temperature (0 C)"].min()
    table.loc[table["Cation"]==cation,"T(Kelvin)"]=str(round(t_min,3))+"-"+str(round(t_max,3))
    p_max=df[df["Cation_Family"]==cation]["Pressure (bar)"].max()
    p_min=df[df["Cation_Family"]==cation]["Pressure (bar)"].min()
    table.loc[table["Cation"]==cation,"P(bar)"]=str(round(p_min,3))+"-"+str(round(p_max,3))
    x_max=df[df["Cation_Family"]==cation]["CO2 capacity (mol CO2/mol IL)"].max()
    x_min=df[df["Cation_Family"]==cation]["CO2 capacity (mol CO2/mol IL)"].min()
    table.loc[table["Cation"]==cation,"xCO2"]=str(round(x_min,3))+"-"+str(round(x_max,3))

In [121]:
table

             Cation    T(Kelvin)        P(bar)         xCO2 Data Points
0       Imidazolium  4.97-139.95     0.0-345.5    0.0-3.115        3851
1          Ammonium    9.95-80.0  0.002-61.211  0.001-8.294         512
2       Phosphonium    20.0-60.0     0.0-60.24    0.0-2.484         272
3         Amidinium    23.0-23.0       1.0-1.0    1.03-1.13           2
4     Pyrrolidinium    9.95-90.0    0.0-199.66    0.0-6.692         374
5        Pyridinium   10.03-60.0   0.002-20.55    0.0-0.603         182
6         Sulfonium    40.0-60.0  0.095-19.006  0.002-0.435          39
7  Cyclopropenylium    40.0-60.0  0.097-18.998  0.002-0.562          39
8      Piperidinium    25.0-70.0  0.099-18.999  0.002-0.524          36
9       Guanidinium  24.95-65.04    1.22-23.95   0.03-0.795          42

In [125]:
table.to_excel("../outputs/tables/cation_summary.xlsx",index=False)

In [124]:
df.to_excel("../data/Solubility_data_with_families.xlsx",index=False)