In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
df=pd.read_csv("../data/DataWithDescriptors.csv")
cation_pka=pd.read_excel("../data/pk_cation.xlsx")
anion_pka=pd.read_excel("../data/pkaanion.xlsx")
print(df.shape)
print(cation_pka.shape)
print(anion_pka.shape)

(5349, 444)
(77, 2)
(80, 2)

In [5]:
cation_pka=cation_pka.rename(columns={ "CATION": 'CATION NAME' })

In [6]:
anion_pka=anion_pka.rename(columns={"Anion":"ANION NAME"})

In [7]:
df = pd.merge(df,cation_pka,on="CATION NAME",how="left")

In [8]:
df = pd.merge(df,anion_pka,on="ANION NAME",how="left")

In [9]:
df["CATION_pKa"].isnull().sum()

np.int64(0)

In [10]:
df["Anion_pKa"].isnull().sum()

np.int64(0)

In [11]:
df["Delta_pKa"] = df["CATION_pKa"] - df["Anion_pKa"]

C:\Users\BIT\AppData\Local\Temp\ipykernel_17084\3233356666.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["Delta_pKa"] = df["CATION_pKa"] - df["Anion_pKa"]

In [12]:
df["Delta_pKa"].describe()

count    5349.000000
mean       14.860804
std         6.282438
min        -4.600000
25%         8.600000
50%        17.500000
75%        20.800000
max        27.500000
Name: Delta_pKa, dtype: float64

In [15]:
df[df["Delta_pKa"] < 2][
    [
        "CATION NAME",
        "ANION NAME",
        "CATION_pKa",
        "Anion_pKa",
        "Delta_pKa"
    ]
]

,CATION NAME,ANION NAME,CATION_pKa,Anion_pKa,Delta_pKa
16,triethylenetetrammonium,piperazine,9.9,9.80,0.10
17,triethylenetetrammonium,imidazolate,9.9,14.50,-4.60
19,triethylenetetrammonium,"1,2,4-triazolate",9.9,10.20,-0.30
36,trihexyl(tetradecyl)phosphonium,phenolate,8.5,9.95,-1.45
37,trihexyl(tetradecyl)phosphonium,p-methylphenolate,8.5,10.30,-1.80
38,trihexyl(tetradecyl)phosphonium,p-chlorophenolate,8.5,9.38,-0.88
39,trihexyl(tetradecyl)phosphonium,p-trifluoromethylphenolate,8.5,8.45,0.05
40,trihexyl(tetradecyl)phosphonium,p-nitrophenolate,8.5,7.15,1.35
41,"N, N-dimethyl-1,3-propane diamine",p-fluorophenolate,10.0,9.95,0.05
47,triethyl(octyl)phosphonium,2-cyanopyrrol-1-ide,8.7,10.50,-1.80

In [16]:
df.describe()

,Unnamed: 0,Temperature (0 C),Pressure (bar),CO2 capacity (mol CO2/mol IL),Cat_MaxAbsEStateIndex,Cat_MaxEStateIndex,Cat_MinAbsEStateIndex,Cat_MinEStateIndex,Cat_qed,Cat_SPS,...,An_fr_term_acetylene,An_fr_tetrazole,An_fr_thiazole,An_fr_thiocyan,An_fr_thiophene,An_fr_unbrch_alkane,An_fr_urea,CATION_pKa,Anion_pKa,Delta_pKa
count,5349.000000,5349.000000,5349.000000,5349.000000,5349.000000,5349.000000,5349.000000,5349.000000,5349.000000,5349.000000,...,5349.0,5349.0,5349.0,5349.000000,5349.0,5349.000000,5349.0,5349.000000,5349.000000,5349.000000
mean,2674.000000,43.361554,16.809779,0.351997,3.113498,3.113498,1.028575,0.863775,0.500547,11.559203,...,0.0,0.0,0.0,0.004300,0.0,0.010282,0.0,8.034231,-6.826573,14.860804
std,1544.267626,21.041986,28.551239,0.556316,2.119076,2.119076,0.295891,1.074778,0.078408,3.697888,...,0.0,0.0,0.0,0.065438,0.0,0.113121,0.0,1.972532,6.027840,6.282438
min,0.000000,4.970000,0.000013,0.000000,2.125000,2.125000,0.122336,-7.856082,0.076609,6.000000,...,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,5.200000,-16.000000,-4.600000
25%,1337.000000,25.000000,2.000000,0.070664,2.211806,2.211806,1.056389,1.056389,0.467050,10.200000,...,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,7.100000,-11.000000,8.600000
50%,2674.000000,40.000000,8.442000,0.186000,2.255899,2.255899,1.150139,1.150139,0.495865,10.285714,...,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,7.200000,-10.000000,17.500000
75%,4011.000000,59.980000,17.100000,0.412429,2.414768,2.414768,1.167500,1.167500,0.554691,10.714286,...,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,7.400000,-0.400000,20.800000
max,5348.000000,139.950000,345.500000,8.293680,13.495084,13.495084,1.366806,1.366806,0.758479,30.454545,...,0.0,0.0,0.0,1.000000,0.0,4.000000,0.0,25.000000,14.500000,27.500000

In [17]:
df.isnull().sum().sum()

np.int64(7992)

In [18]:
miss_val_cols=df.columns[df.isnull().sum()>0]

In [19]:
len(miss_val_cols)

12

In [20]:
df=df.drop(columns=miss_val_cols)

In [21]:
df=df.drop(columns="Unnamed: 0")

In [22]:
df.isnull().sum().sum()

np.int64(0)

In [23]:
const=[]
for col in df.columns:
    if df[col].nunique()==1:
        const.append(col)

In [25]:
len(const)

125

In [26]:
df.drop(columns=const,inplace=True)

In [27]:
unuseful_cols=['IL NAME', 'CATION NAME', 'ANION NAME', 'Cation_SMILES', 'Anion_SMILES','Cation_Family','Delta_pKa']

In [28]:
df_model=df.drop(columns=unuseful_cols)

In [29]:
X=df_model.drop(columns=["CO2 capacity (mol CO2/mol IL)"])
Y=df_model["CO2 capacity (mol CO2/mol IL)"]

In [30]:
from sklearn.model_selection import train_test_split

In [31]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [32]:
print(X_train.shape,X_test.shape,y_train.shape, y_test.shape)

(4279, 301) (1070, 301) (4279,) (1070,)

In [33]:
constant_cols = []

for col in X_train.columns:

    if X_train[col].nunique() == 1:

        constant_cols.append(col)

print("Constant Features:", len(constant_cols))

Constant Features: 2

In [34]:
X_train = X_train.drop(
    columns=constant_cols
)

X_test = X_test.drop(
    columns=constant_cols
)

In [35]:
from sklearn.feature_selection import VarianceThreshold

selector = VarianceThreshold(threshold=0.001)

selector.fit(X_train)

VarianceThreshold(threshold=0.001)

In [36]:
selected_cols=X_train.columns[selector.get_support()]
X_train_low_var = X_train[selected_cols]
X_test_low_var = X_test[selected_cols]

In [37]:
print(X_train.shape,X_train_low_var.shape)

(4279, 299) (4279, 288)

In [38]:
X_train = X_train_low_var.copy()
X_test = X_test_low_var.copy()

In [39]:
corr=X_train.corr().abs()

In [40]:
upper = corr.where(np.triu(np.ones(corr.shape),k=1).astype(bool))

In [41]:
to_drop = []

for col in upper.columns:

    if any(upper[col] > 0.975):

        to_drop.append(col)

In [42]:
len(to_drop)

76

In [43]:
X_train_corr = X_train.drop(
    columns=to_drop
)

X_test_corr = X_test.drop(
    columns=to_drop
)

In [44]:
from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(
    n_estimators=200,
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train_corr, y_train)

RandomForestRegressor(n_estimators=200, n_jobs=-1, random_state=42)

In [56]:
importance = pd.DataFrame({
    "Feature": X_train_corr.columns,
    "Importance": rf.feature_importances_
})

importance = importance.sort_values(
    by="Importance",
    ascending=False
)

importance.head(30)

                Feature  Importance
1        Pressure (bar)    0.500899
0     Temperature (0 C)    0.072975
96          Cat_MolLogP    0.037933
123         An_BalabanJ    0.034575
74      Cat_EState_VSA9    0.023660
211           Anion_pKa    0.019980
76      Cat_VSA_EState3    0.017950
131              An_Ipc    0.016724
26            Cat_Chi0n    0.015214
55         Cat_SMR_VSA5    0.014789
67      Cat_EState_VSA2    0.014587
28            Cat_Chi2n    0.014230
73      Cat_EState_VSA8    0.013110
33            Cat_Chi4v    0.012871
20   Cat_BCUT2D_LOGPLOW    0.012305
29            Cat_Chi2v    0.010571
65             Cat_TPSA    0.010529
21      Cat_BCUT2D_MRHI    0.009077
127            An_Chi3n    0.009042
141        An_PEOE_VSA3    0.008238
19    Cat_BCUT2D_LOGPHI    0.007925
83        Cat_NHOHCount    0.007582
122           An_AvgIpc    0.007302
38        Cat_PEOE_VSA1    0.006501
166             An_TPSA    0.006478
32            Cat_Chi4n    0.006083
117              An_qed    0.005919
155       An_SlogP_VSA1    0.005845
91       Cat_NumHDonors    0.005745
51         Cat_SMR_VSA1    0.004005

In [57]:
rf_top20 = set(importance.head(20)["Feature"])

In [58]:
rf_features = importance["Feature"].head(20).tolist()

In [59]:
rf_features = importance["Feature"].head(20).tolist()

X_rf_train = X_train_corr[rf_features]
X_rf_test = X_test_corr[rf_features]

print(X_rf_train.shape)
print(X_rf_test.shape)

(4279, 20)
(1070, 20)

In [60]:
pd.DataFrame(
    rf_features,
    columns=["Descriptor"]
).to_excel("../outputs/tables/RF_Top20_FeaturesWithpKa.xlsx",
    index=False
)

In [61]:
X_rf_train.to_csv("../data/X_rf_trainpKa.csv", index=False)
X_rf_test.to_csv("../data/X_rf_testpKa.csv", index=False)

y_train.to_csv("../data/y_trainpKa.csv", index=False)
y_test.to_csv("../data/y_testpKa.csv", index=False)