In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
X_train=pd.read_csv("../data/X_rf_train.csv")
X_test=pd.read_csv("../data/X_rf_test.csv")
y_train=pd.read_csv("../data/y_train.csv")
y_test=pd.read_csv("../data/y_test.csv")

In [3]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(4279, 20)
(1070, 20)
(4279, 1)
(1070, 1)

In [4]:
y_train=y_train.squeeze()
y_test=y_test.squeeze()

In [5]:
print(y_train.shape)
print(y_test.shape)

(4279,)
(1070,)

In [2]:
import xgboost as xgb

In [7]:
model = xgb.XGBRegressor(objective='reg:squarederror',n_estimators=100, random_state=42)

In [8]:
model.fit(X_train,y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=None, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=100,
             n_jobs=None, num_parallel_tree=None, ...)

In [9]:
y_train_pred=model.predict(X_train)
y_pred=model.predict(X_test)

In [10]:
from sklearn.metrics import(r2_score,mean_absolute_error,mean_squared_error)
r2=r2_score(y_test,y_pred)
mae = mean_absolute_error(y_test,y_pred)
rmse = np.sqrt(mean_squared_error(y_test,y_pred))

In [11]:
train_r2 = r2_score(y_train,y_train_pred)
print("Train R2:", round(train_r2,4))

Train R2: 0.999

In [12]:
print("TEST METRICS ARE")
print("R2 :", round(r2,4))
print("MAE :", round(mae,4))
print("RMSE :", round(rmse,4))

TEST METRICS ARE
R2 : 0.9799
MAE : 0.0311
RMSE : 0.0813

In [13]:
from sklearn.model_selection import cross_val_score
cv_scores = cross_val_score(model,X_train,y_train,cv=10,scoring="r2",n_jobs=-1)
print("Fold Scores:")
print(cv_scores)
print()
print("Mean CV R2:",round(cv_scores.mean(),4))
print("Std CV R2:",round(cv_scores.std(),4))

Fold Scores:
[0.982736   0.96831825 0.98434163 0.98517771 0.96687794 0.98263743
 0.98206371 0.98333739 0.98572613 0.98380139]

Mean CV R2: 0.9805
Std CV R2: 0.0065

In [28]:
pip install optuna

Requirement already satisfied: optuna in c:\CO2_solubility_Ionic_Liquids\venv\Lib\site-packages (4.9.0)
Requirement already satisfied: alembic>=1.5.0 in c:\CO2_solubility_Ionic_Liquids\venv\Lib\site-packages (from optuna) (1.18.4)
Requirement already satisfied: colorlog in c:\CO2_solubility_Ionic_Liquids\venv\Lib\site-packages (from optuna) (6.10.1)
Requirement already satisfied: numpy in c:\CO2_solubility_Ionic_Liquids\venv\Lib\site-packages (from optuna) (2.4.6)
Requirement already satisfied: packaging>=20.0 in c:\CO2_solubility_Ionic_Liquids\venv\Lib\site-packages (from optuna) (26.2)
Requirement already satisfied: sqlalchemy>=1.4.2 in c:\CO2_solubility_Ionic_Liquids\venv\Lib\site-packages (from optuna) (2.0.50)
Requirement already satisfied: tqdm in c:\CO2_solubility_Ionic_Liquids\venv\Lib\site-packages (from optuna) (4.68.2)
Requirement already satisfied: PyYAML in c:\CO2_solubility_Ionic_Liquids\venv\Lib\site-packages (from optuna) (6.0.3)
Requirement already satisfied: Mako in c:\CO2_solubility_Ionic_Liquids\venv\Lib\site-packages (from alembic>=1.5.0->optuna) (1.3.12)
Requirement already satisfied: typing-extensions>=4.12 in c:\CO2_solubility_Ionic_Liquids\venv\Lib\site-packages (from alembic>=1.5.0->optuna) (4.15.0)
Requirement already satisfied: greenlet>=1 in c:\CO2_solubility_Ionic_Liquids\venv\Lib\site-packages (from sqlalchemy>=1.4.2->optuna) (3.5.1)
Requirement already satisfied: colorama in c:\CO2_solubility_Ionic_Liquids\venv\Lib\site-packages (from colorlog->optuna) (0.4.6)
Requirement already satisfied: MarkupSafe>=0.9.2 in c:\CO2_solubility_Ionic_Liquids\venv\Lib\site-packages (from Mako->alembic>=1.5.0->optuna) (3.0.3)
Note: you may need to restart the kernel to use updated packages.

In [35]:
import optuna
from xgboost import XGBRegressor

In [40]:
def objective(trial):

    xgb_model = XGBRegressor(

        objective="reg:squarederror",

        n_estimators=trial.suggest_int(
            "n_estimators",
            100,
            1000
        ),

        max_depth=trial.suggest_int(
            "max_depth",
            3,
            10
        ),

        learning_rate=trial.suggest_float(
            "learning_rate",
            0.01,
            0.3,
            log=True
        ),

        subsample=trial.suggest_float(
            "subsample",
            0.6,
            1.0
        ),

        colsample_bytree=trial.suggest_float(
            "colsample_bytree",
            0.6,
            1.0
        ),

        min_child_weight=trial.suggest_int(
            "min_child_weight",
            1,
            10
        ),

        gamma=trial.suggest_float(
            "gamma",
            0,
            5
        ),

        random_state=42,

        n_jobs=-1
    )

    scores = cross_val_score(
        xgb_model,
        X_train,
        y_train,
        cv=10,
        scoring="r2",
        n_jobs=-1
    )

    return scores.mean()

In [41]:
study = optuna.create_study(
    direction="maximize"
)

study.optimize(
    objective,
    n_trials=50
)

[I 2026-06-11 16:25:16,971] A new study created in memory with name: no-name-27b62355-f0c5-414c-a345-58ea7a4c218e

[I 2026-06-11 16:25:23,511] Trial 0 finished with value: 0.863991212315484 and parameters: {'n_estimators': 462, 'max_depth': 6, 'learning_rate': 0.07510561464804204, 'subsample': 0.9879792665708218, 'colsample_bytree': 0.8965284543101149, 'min_child_weight': 6, 'gamma': 4.213045349970361}. Best is trial 0 with value: 0.863991212315484.
[I 2026-06-11 16:25:26,691] Trial 1 finished with value: 0.9287270571791681 and parameters: {'n_estimators': 513, 'max_depth': 8, 'learning_rate': 0.08510659614300083, 'subsample': 0.8383137974253241, 'colsample_bytree': 0.9022032203373171, 'min_child_weight': 9, 'gamma': 0.7260305937218475}. Best is trial 1 with value: 0.9287270571791681.
[I 2026-06-11 16:25:26,967] Trial 2 finished with value: 0.808290188904406 and parameters: {'n_estimators': 126, 'max_depth': 7, 'learning_rate': 0.01397296393087988, 'subsample': 0.8340078100274374, 'colsample_bytree': 0.7159756209188589, 'min_child_weight': 6, 'gamma': 2.0430001475046833}. Best is trial 1 with value: 0.9287270571791681.
[I 2026-06-11 16:25:27,684] Trial 3 finished with value: 0.8811339347431822 and parameters: {'n_estimators': 898, 'max_depth': 8, 'learning_rate': 0.01859371563840559, 'subsample': 0.6473429229766858, 'colsample_bytree': 0.675024773116326, 'min_child_weight': 6, 'gamma': 2.4118687177766436}. Best is trial 1 with value: 0.9287270571791681.
[I 2026-06-11 16:25:28,035] Trial 4 finished with value: 0.9295734257734114 and parameters: {'n_estimators': 493, 'max_depth': 6, 'learning_rate': 0.20000456691698987, 'subsample': 0.9256482971950661, 'colsample_bytree': 0.8411999474895102, 'min_child_weight': 5, 'gamma': 0.8922449944050692}. Best is trial 4 with value: 0.9295734257734114.
[I 2026-06-11 16:25:28,510] Trial 5 finished with value: 0.8537268667710134 and parameters: {'n_estimators': 644, 'max_depth': 9, 'learning_rate': 0.07633179138314217, 'subsample': 0.6345555407452848, 'colsample_bytree': 0.9683424642091014, 'min_child_weight': 6, 'gamma': 4.217185458690969}. Best is trial 4 with value: 0.9295734257734114.
[I 2026-06-11 16:25:28,922] Trial 6 finished with value: 0.8829793940721921 and parameters: {'n_estimators': 570, 'max_depth': 5, 'learning_rate': 0.05205202973835035, 'subsample': 0.9834982340196604, 'colsample_bytree': 0.9993673040379238, 'min_child_weight': 5, 'gamma': 2.855651207619205}. Best is trial 4 with value: 0.9295734257734114.
[I 2026-06-11 16:25:29,426] Trial 7 finished with value: 0.826969280803757 and parameters: {'n_estimators': 792, 'max_depth': 3, 'learning_rate': 0.07405874432194536, 'subsample': 0.983316668554868, 'colsample_bytree': 0.6672020597660437, 'min_child_weight': 10, 'gamma': 4.521745211573305}. Best is trial 4 with value: 0.9295734257734114.
[I 2026-06-11 16:25:30,093] Trial 8 finished with value: 0.877635880403874 and parameters: {'n_estimators': 937, 'max_depth': 8, 'learning_rate': 0.12326894343182052, 'subsample': 0.6960265049660712, 'colsample_bytree': 0.7725727021993375, 'min_child_weight': 3, 'gamma': 3.1954645141176874}. Best is trial 4 with value: 0.9295734257734114.
[I 2026-06-11 16:25:30,433] Trial 9 finished with value: 0.9353849650921049 and parameters: {'n_estimators': 206, 'max_depth': 9, 'learning_rate': 0.02444027944194631, 'subsample': 0.778562545207321, 'colsample_bytree': 0.9966124749432319, 'min_child_weight': 3, 'gamma': 0.7956834484624015}. Best is trial 9 with value: 0.9353849650921049.
[I 2026-06-11 16:25:31,773] Trial 10 finished with value: 0.9351683165887268 and parameters: {'n_estimators': 129, 'max_depth': 10, 'learning_rate': 0.029535284217349703, 'subsample': 0.7559101274912828, 'colsample_bytree': 0.622605912388628, 'min_child_weight': 1, 'gamma': 0.02053096915907826}. Best is trial 9 with value: 0.9353849650921049.
[I 2026-06-11 16:25:33,502] Trial 11 finished with value: 0.9105648783769216 and parameters: {'n_estimators': 105, 'max_depth': 10, 'learning_rate': 0.028852988874617104, 'subsample': 0.7592026400201504, 'colsample_bytree': 0.6060614665310686, 'min_child_weight': 1, 'gamma': 0.003147924477938248}. Best is trial 9 with value: 0.9353849650921049.
[I 2026-06-11 16:25:33,851] Trial 12 finished with value: 0.9199969643437852 and parameters: {'n_estimators': 287, 'max_depth': 10, 'learning_rate': 0.03064765412641257, 'subsample': 0.7682450947534729, 'colsample_bytree': 0.7932762973636875, 'min_child_weight': 1, 'gamma': 1.1940278610035566}. Best is trial 9 with value: 0.9353849650921049.
[I 2026-06-11 16:25:34,498] Trial 13 finished with value: 0.9547225155291195 and parameters: {'n_estimators': 286, 'max_depth': 10, 'learning_rate': 0.030817034140330386, 'subsample': 0.7541215276976009, 'colsample_bytree': 0.6145210121256063, 'min_child_weight': 3, 'gamma': 0.1453607018812818}. Best is trial 13 with value: 0.9547225155291195.
[I 2026-06-11 16:25:34,969] Trial 14 finished with value: 0.8957962560267683 and parameters: {'n_estimators': 293, 'max_depth': 9, 'learning_rate': 0.010754431431889915, 'subsample': 0.8312057283149341, 'colsample_bytree': 0.7520886072294454, 'min_child_weight': 3, 'gamma': 1.5440148898859114}. Best is trial 13 with value: 0.9547225155291195.
[I 2026-06-11 16:25:35,376] Trial 15 finished with value: 0.9465739932847305 and parameters: {'n_estimators': 314, 'max_depth': 9, 'learning_rate': 0.041876710958445536, 'subsample': 0.710045469446948, 'colsample_bytree': 0.8508682780524878, 'min_child_weight': 3, 'gamma': 0.4840099460773395}. Best is trial 13 with value: 0.9547225155291195.
[I 2026-06-11 16:25:35,803] Trial 16 finished with value: 0.945550986079916 and parameters: {'n_estimators': 362, 'max_depth': 10, 'learning_rate': 0.04563314274670889, 'subsample': 0.7100120425229917, 'colsample_bytree': 0.8411340009303787, 'min_child_weight': 4, 'gamma': 0.48093312895686235}. Best is trial 13 with value: 0.9547225155291195.
[I 2026-06-11 16:25:36,192] Trial 17 finished with value: 0.9156299805686479 and parameters: {'n_estimators': 389, 'max_depth': 9, 'learning_rate': 0.04515886158869733, 'subsample': 0.6924454169868969, 'colsample_bytree': 0.9194440346854552, 'min_child_weight': 2, 'gamma': 1.405843485513362}. Best is trial 13 with value: 0.9547225155291195.
[I 2026-06-11 16:25:36,435] Trial 18 finished with value: 0.8740358370140384 and parameters: {'n_estimators': 251, 'max_depth': 3, 'learning_rate': 0.2588268025315541, 'subsample': 0.8895375009035976, 'colsample_bytree': 0.8260317057999347, 'min_child_weight': 8, 'gamma': 1.771815313836341}. Best is trial 13 with value: 0.9547225155291195.
[I 2026-06-11 16:25:37,156] Trial 19 finished with value: 0.94440944927643 and parameters: {'n_estimators': 658, 'max_depth': 7, 'learning_rate': 0.018568923446807672, 'subsample': 0.6689474075507099, 'colsample_bytree': 0.7175332076566534, 'min_child_weight': 4, 'gamma': 0.4415285156219509}. Best is trial 13 with value: 0.9547225155291195.
[I 2026-06-11 16:25:37,547] Trial 20 finished with value: 0.9498599176986297 and parameters: {'n_estimators': 402, 'max_depth': 8, 'learning_rate': 0.12426679224997589, 'subsample': 0.7218523805519428, 'colsample_bytree': 0.6609574542357897, 'min_child_weight': 2, 'gamma': 0.2650548781249723}. Best is trial 13 with value: 0.9547225155291195.
[I 2026-06-11 16:25:37,959] Trial 21 finished with value: 0.9509313040839686 and parameters: {'n_estimators': 393, 'max_depth': 8, 'learning_rate': 0.13428292229894925, 'subsample': 0.726505200716221, 'colsample_bytree': 0.6493622898143133, 'min_child_weight': 2, 'gamma': 0.2256358203255725}. Best is trial 13 with value: 0.9547225155291195.
[I 2026-06-11 16:25:38,360] Trial 22 finished with value: 0.9516422134043563 and parameters: {'n_estimators': 401, 'max_depth': 7, 'learning_rate': 0.14592642108996332, 'subsample': 0.6045419308140394, 'colsample_bytree': 0.6498981730123755, 'min_child_weight': 2, 'gamma': 0.18592560558216742}. Best is trial 13 with value: 0.9547225155291195.
[I 2026-06-11 16:25:38,590] Trial 23 finished with value: 0.9124110490317904 and parameters: {'n_estimators': 211, 'max_depth': 7, 'learning_rate': 0.1618767721418608, 'subsample': 0.616713419144408, 'colsample_bytree': 0.6348767728913398, 'min_child_weight': 2, 'gamma': 1.0707544478845428}. Best is trial 13 with value: 0.9547225155291195.
[I 2026-06-11 16:25:38,974] Trial 24 finished with value: 0.9544034964030741 and parameters: {'n_estimators': 433, 'max_depth': 5, 'learning_rate': 0.2522751429235908, 'subsample': 0.8006481026332312, 'colsample_bytree': 0.697807627301369, 'min_child_weight': 2, 'gamma': 0.11009387474158018}. Best is trial 13 with value: 0.9547225155291195.
[I 2026-06-11 16:25:39,440] Trial 25 finished with value: 0.9157403816972088 and parameters: {'n_estimators': 584, 'max_depth': 4, 'learning_rate': 0.27970956116020507, 'subsample': 0.7925637043628151, 'colsample_bytree': 0.7024366768100622, 'min_child_weight': 4, 'gamma': 0.7430095340670578}. Best is trial 13 with value: 0.9547225155291195.
[I 2026-06-11 16:25:39,832] Trial 26 finished with value: 0.9618027698155437 and parameters: {'n_estimators': 442, 'max_depth': 5, 'learning_rate': 0.20614559546502187, 'subsample': 0.867671006407685, 'colsample_bytree': 0.6012757489716011, 'min_child_weight': 1, 'gamma': 0.052859439558327434}. Best is trial 26 with value: 0.9618027698155437.
[I 2026-06-11 16:25:40,388] Trial 27 finished with value: 0.9175503251199183 and parameters: {'n_estimators': 732, 'max_depth': 5, 'learning_rate': 0.20461001599124182, 'subsample': 0.8863600687993067, 'colsample_bytree': 0.6003723854892029, 'min_child_weight': 1, 'gamma': 1.0564704097042537}. Best is trial 26 with value: 0.9618027698155437.
[I 2026-06-11 16:25:40,779] Trial 28 finished with value: 0.9260642521788179 and parameters: {'n_estimators': 471, 'max_depth': 4, 'learning_rate': 0.21200045613147003, 'subsample': 0.7991705565062579, 'colsample_bytree': 0.6952491880183181, 'min_child_weight': 1, 'gamma': 0.5577057364040612}. Best is trial 26 with value: 0.9618027698155437.
[I 2026-06-11 16:25:41,250] Trial 29 finished with value: 0.871838485547317 and parameters: {'n_estimators': 553, 'max_depth': 5, 'learning_rate': 0.09886813343773973, 'subsample': 0.8763086846091226, 'colsample_bytree': 0.743985983008594, 'min_child_weight': 3, 'gamma': 3.5139595904210377}. Best is trial 26 with value: 0.9618027698155437.
[I 2026-06-11 16:25:41,666] Trial 30 finished with value: 0.9046173460055515 and parameters: {'n_estimators': 433, 'max_depth': 6, 'learning_rate': 0.05933415818782916, 'subsample': 0.9441140159286326, 'colsample_bytree': 0.6238875420015093, 'min_child_weight': 7, 'gamma': 1.3757856176007417}. Best is trial 26 with value: 0.9618027698155437.
[I 2026-06-11 16:25:42,096] Trial 31 finished with value: 0.9786194367444143 and parameters: {'n_estimators': 346, 'max_depth': 4, 'learning_rate': 0.16719814246360432, 'subsample': 0.8609485028990599, 'colsample_bytree': 0.6418499469653057, 'min_child_weight': 2, 'gamma': 0.0006471760938816656}. Best is trial 31 with value: 0.9786194367444143.
[I 2026-06-11 16:25:42,474] Trial 32 finished with value: 0.9809816085552413 and parameters: {'n_estimators': 337, 'max_depth': 4, 'learning_rate': 0.2988939627715043, 'subsample': 0.8629215284372397, 'colsample_bytree': 0.6833721303155229, 'min_child_weight': 2, 'gamma': 0.001608288196587743}. Best is trial 32 with value: 0.9809816085552413.
[I 2026-06-11 16:25:42,746] Trial 33 finished with value: 0.9214844983649453 and parameters: {'n_estimators': 336, 'max_depth': 4, 'learning_rate': 0.18352186914430868, 'subsample': 0.8588596422927003, 'colsample_bytree': 0.6343379191909242, 'min_child_weight': 4, 'gamma': 0.5307055795453777}. Best is trial 32 with value: 0.9809816085552413.
[I 2026-06-11 16:25:42,961] Trial 34 finished with value: 0.9479184898645794 and parameters: {'n_estimators': 187, 'max_depth': 3, 'learning_rate': 0.10065851070665126, 'subsample': 0.9121714311502649, 'colsample_bytree': 0.6794111650056921, 'min_child_weight': 2, 'gamma': 0.0022646922910374845}. Best is trial 32 with value: 0.9809816085552413.
[I 2026-06-11 16:25:43,181] Trial 35 finished with value: 0.9152220195843469 and parameters: {'n_estimators': 248, 'max_depth': 4, 'learning_rate': 0.29009783819406276, 'subsample': 0.8381823646012739, 'colsample_bytree': 0.603504928865842, 'min_child_weight': 1, 'gamma': 0.8629633221880169}. Best is trial 32 with value: 0.9809816085552413.
[I 2026-06-11 16:25:43,577] Trial 36 finished with value: 0.9289147838609523 and parameters: {'n_estimators': 524, 'max_depth': 4, 'learning_rate': 0.23097799647156972, 'subsample': 0.947379829861952, 'colsample_bytree': 0.646174893025706, 'min_child_weight': 5, 'gamma': 0.32939643926800666}. Best is trial 32 with value: 0.9809816085552413.
[I 2026-06-11 16:25:43,881] Trial 37 finished with value: 0.9375333700621367 and parameters: {'n_estimators': 346, 'max_depth': 6, 'learning_rate': 0.1697125042216771, 'subsample': 0.8574776258884161, 'colsample_bytree': 0.7262100729856864, 'min_child_weight': 3, 'gamma': 0.5916188256589042}. Best is trial 32 with value: 0.9809816085552413.
[I 2026-06-11 16:25:44,248] Trial 38 finished with value: 0.873920589482178 and parameters: {'n_estimators': 473, 'max_depth': 3, 'learning_rate': 0.10378569440162355, 'subsample': 0.82456405195913, 'colsample_bytree': 0.6778941921082569, 'min_child_weight': 2, 'gamma': 1.8830611623447755}. Best is trial 32 with value: 0.9809816085552413.
[I 2026-06-11 16:25:44,472] Trial 39 finished with value: 0.9144378894380036 and parameters: {'n_estimators': 165, 'max_depth': 5, 'learning_rate': 0.06549982634121497, 'subsample': 0.9105884286703392, 'colsample_bytree': 0.6171929089909488, 'min_child_weight': 4, 'gamma': 0.9261479408188281}. Best is trial 32 with value: 0.9809816085552413.
[I 2026-06-11 16:25:44,918] Trial 40 finished with value: 0.923422699562626 and parameters: {'n_estimators': 264, 'max_depth': 6, 'learning_rate': 0.013999437930132074, 'subsample': 0.8144477011897014, 'colsample_bytree': 0.667944547377928, 'min_child_weight': 5, 'gamma': 0.3003594883160501}. Best is trial 32 with value: 0.9809816085552413.
[I 2026-06-11 16:25:45,302] Trial 41 finished with value: 0.9746029244995169 and parameters: {'n_estimators': 435, 'max_depth': 5, 'learning_rate': 0.24886592332807322, 'subsample': 0.8573656580189246, 'colsample_bytree': 0.6900748360033505, 'min_child_weight': 2, 'gamma': 0.010803515315663802}. Best is trial 32 with value: 0.9809816085552413.
[I 2026-06-11 16:25:45,619] Trial 42 finished with value: 0.9183479215174634 and parameters: {'n_estimators': 440, 'max_depth': 4, 'learning_rate': 0.299216724112842, 'subsample': 0.8584951344198574, 'colsample_bytree': 0.6883169624724683, 'min_child_weight': 3, 'gamma': 0.6841954095604246}. Best is trial 32 with value: 0.9809816085552413.
[I 2026-06-11 16:25:46,060] Trial 43 finished with value: 0.9467534009628155 and parameters: {'n_estimators': 524, 'max_depth': 5, 'learning_rate': 0.2275210942117183, 'subsample': 0.8734599141416495, 'colsample_bytree': 0.6330871116288511, 'min_child_weight': 1, 'gamma': 0.2396335937138891}. Best is trial 32 with value: 0.9809816085552413.
[I 2026-06-11 16:25:46,520] Trial 44 finished with value: 0.9496317750036086 and parameters: {'n_estimators': 619, 'max_depth': 3, 'learning_rate': 0.18172503803433612, 'subsample': 0.952786506002731, 'colsample_bytree': 0.6574944661213165, 'min_child_weight': 2, 'gamma': 0.04950801778850197}. Best is trial 32 with value: 0.9809816085552413.
[I 2026-06-11 16:25:46,792] Trial 45 finished with value: 0.9416398325642996 and parameters: {'n_estimators': 325, 'max_depth': 5, 'learning_rate': 0.15166316631168458, 'subsample': 0.9142017358559817, 'colsample_bytree': 0.7133375252172379, 'min_child_weight': 1, 'gamma': 0.3736976683734588}. Best is trial 32 with value: 0.9809816085552413.
[I 2026-06-11 16:25:47,206] Trial 46 finished with value: 0.9318544612621388 and parameters: {'n_estimators': 504, 'max_depth': 6, 'learning_rate': 0.22682485908314595, 'subsample': 0.8472958293201363, 'colsample_bytree': 0.7308709613414688, 'min_child_weight': 3, 'gamma': 0.7066674003480906}. Best is trial 32 with value: 0.9809816085552413.
[I 2026-06-11 16:25:47,451] Trial 47 finished with value: 0.9667470876058515 and parameters: {'n_estimators': 229, 'max_depth': 4, 'learning_rate': 0.1960800277698226, 'subsample': 0.894106146033299, 'colsample_bytree': 0.6159292769200156, 'min_child_weight': 1, 'gamma': 0.015557437274908777}. Best is trial 32 with value: 0.9809816085552413.
[I 2026-06-11 16:25:47,715] Trial 48 finished with value: 0.9724935816678594 and parameters: {'n_estimators': 231, 'max_depth': 4, 'learning_rate': 0.1909138491275782, 'subsample': 0.9036045507645624, 'colsample_bytree': 0.7553266552730287, 'min_child_weight': 1, 'gamma': 0.008070923621856315}. Best is trial 32 with value: 0.9809816085552413.
[I 2026-06-11 16:25:47,933] Trial 49 finished with value: 0.933182697664682 and parameters: {'n_estimators': 229, 'max_depth': 4, 'learning_rate': 0.11433396315758475, 'subsample': 0.9313413646921762, 'colsample_bytree': 0.7728971972472101, 'min_child_weight': 1, 'gamma': 0.40013770281761396}. Best is trial 32 with value: 0.9809816085552413.

In [42]:
print("Best CV R2:")
print(study.best_value)

print()

print("Best Parameters:")
print(study.best_params)

Best CV R2:
0.9809816085552413

Best Parameters:
{'n_estimators': 337, 'max_depth': 4, 'learning_rate': 0.2988939627715043, 'subsample': 0.8629215284372397, 'colsample_bytree': 0.6833721303155229, 'min_child_weight': 2, 'gamma': 0.001608288196587743}

In [43]:
best_xgb = XGBRegressor(
    objective="reg:squarederror",
    **study.best_params,
    random_state=42,
    n_jobs=-1
)

best_xgb.fit(
    X_train,
    y_train
)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=0.6833721303155229, device=None,
             early_stopping_rounds=None, enable_categorical=False,
             eval_metric=None, feature_types=None, feature_weights=None,
             gamma=0.001608288196587743, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=0.2988939627715043,
             max_bin=None, max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=4, max_leaves=None,
             min_child_weight=2, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=337, n_jobs=-1,
             num_parallel_tree=None, ...)

In [44]:
y_train_pred = best_xgb.predict(X_train)
y_test_pred = best_xgb.predict(X_test)

In [45]:
from sklearn.metrics import(r2_score,mean_absolute_error,mean_squared_error)
r2=r2_score(y_test,y_pred)
mae = mean_absolute_error(y_test,y_pred)
rmse = np.sqrt(mean_squared_error(y_test,y_pred))

In [46]:
train_r2 = r2_score(y_train,y_train_pred)
print("Train R2:", round(train_r2,4))

Train R2: 0.9972

In [47]:
print("TEST METRICS ARE")
print("R2 :", round(r2,4))
print("MAE :", round(mae,4))
print("RMSE :", round(rmse,4))

TEST METRICS ARE
R2 : 0.9799
MAE : 0.0311
RMSE : 0.0813

In [ ]:
from sklearn.model_selection import cross_val_score
cv_scores = cross_val_score(model,X_train,y_train,cv=10,scoring="r2",n_jobs=-1)
print("Fold Scores:")
print(cv_scores)
print()
print("Mean CV R2:",round(cv_scores.mean(),4))
print("Std CV R2:",round(cv_scores.std(),4))

Fold Scores:
[0.982736   0.96831825 0.98434163 0.98517771 0.96687794 0.98263743
 0.98206371 0.98333739 0.98572613 0.98380139]

Mean CV R2: 0.9805
Std CV R2: 0.0065

:

In [14]:
df=pd.read_csv("../data/DataWithDescriptors.csv")
df.columns

Index(['Unnamed: 0', 'IL NAME', 'CATION NAME', 'ANION NAME', 'Cation_SMILES',
       'Anion_SMILES', 'Temperature (0 C)', 'Pressure (bar)',
       'CO2 capacity (mol CO2/mol IL)', 'Cation_Family',
       ...
       'An_fr_sulfide', 'An_fr_sulfonamd', 'An_fr_sulfone',
       'An_fr_term_acetylene', 'An_fr_tetrazole', 'An_fr_thiazole',
       'An_fr_thiocyan', 'An_fr_thiophene', 'An_fr_unbrch_alkane',
       'An_fr_urea'],
      dtype='str', length=444)

In [15]:
features=pd.read_excel("../data/RF_Top20_Features.xlsx")
features

            Descriptor
0       Pressure (bar)
1    Temperature (0 C)
2          Cat_MolLogP
3      Cat_EState_VSA2
4              An_TPSA
5      Cat_VSA_EState3
6            An_AvgIpc
7        An_SlogP_VSA1
8             Cat_TPSA
9      Cat_EState_VSA9
10  Cat_BCUT2D_LOGPLOW
11      Cat_NumHDonors
12        Cat_SMR_VSA5
13        Cat_SMR_VSA1
14       Cat_PEOE_VSA1
15       Cat_NHOHCount
16     Cat_EState_VSA8
17           Cat_Chi4v
18         An_BalabanJ
19        An_PEOE_VSA3

In [16]:
rf_features = features.iloc[:,0].tolist()

print(rf_features)
print(len(rf_features))

['Pressure (bar)', 'Temperature (0 C)', 'Cat_MolLogP', 'Cat_EState_VSA2', 'An_TPSA', 'Cat_VSA_EState3', 'An_AvgIpc', 'An_SlogP_VSA1', 'Cat_TPSA', 'Cat_EState_VSA9', 'Cat_BCUT2D_LOGPLOW', 'Cat_NumHDonors', 'Cat_SMR_VSA5', 'Cat_SMR_VSA1', 'Cat_PEOE_VSA1', 'Cat_NHOHCount', 'Cat_EState_VSA8', 'Cat_Chi4v', 'An_BalabanJ', 'An_PEOE_VSA3']
20

In [17]:
ranged_df=df[(df["Temperature (0 C)"] >= 25) &(df["Temperature (0 C)"] <= 30) &(df["Pressure (bar)"] >= 0.5) &(df["Pressure (bar)"] <= 1.5)].copy()

In [18]:
ranged_df.describe()

,Unnamed: 0,Temperature (0 C),Pressure (bar),CO2 capacity (mol CO2/mol IL),Cat_MaxAbsEStateIndex,Cat_MaxEStateIndex,Cat_MinAbsEStateIndex,Cat_MinEStateIndex,Cat_qed,Cat_SPS,...,An_fr_sulfide,An_fr_sulfonamd,An_fr_sulfone,An_fr_term_acetylene,An_fr_tetrazole,An_fr_thiazole,An_fr_thiocyan,An_fr_thiophene,An_fr_unbrch_alkane,An_fr_urea
count,146.000000,146.000000,146.000000,146.000000,146.000000,146.000000,146.000000,146.000000,146.000000,146.000000,...,146.000000,146.000000,146.0,146.0,146.0,146.0,146.0,146.0,146.000000,146.0
mean,2130.917808,26.805822,0.937501,0.233495,3.115569,3.115569,1.035509,0.733522,0.475782,11.631347,...,0.006849,0.506849,0.0,0.0,0.0,0.0,0.0,0.0,0.068493,0.0
std,1585.237254,2.370709,0.277405,0.389334,1.868038,1.868038,0.252641,1.289823,0.148699,3.756898,...,0.082761,0.872939,0.0,0.0,0.0,0.0,0.0,0.0,0.400991,0.0
min,14.000000,25.000000,0.500000,0.003412,2.125000,2.125000,0.122336,-7.856082,0.076609,9.428571,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
25%,374.250000,25.000000,0.751500,0.021946,2.211806,2.211806,1.056389,1.056389,0.461795,9.909091,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
50%,2182.500000,25.010000,0.999000,0.039506,2.365434,2.365434,1.150139,1.150139,0.541779,10.200000,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
75%,3458.750000,30.000000,1.000000,0.214690,3.674173,3.674173,1.155926,1.155926,0.578815,11.583333,...,0.000000,1.500000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
max,4971.000000,30.000000,1.500000,2.050000,13.495084,13.495084,1.364796,1.364796,0.758479,24.666667,...,1.000000,2.000000,0.0,0.0,0.0,0.0,0.0,0.0,4.000000,0.0

In [23]:
ranged_df["XG_Pred"] = model.predict(ranged_df[rf_features])

In [24]:
print(
    "Unique ILs:",
    ranged_df["IL NAME"].nunique()
)

Unique ILs: 72

In [26]:
rf_ranking = (ranged_df.groupby("IL NAME")["XG_Pred"].mean().reset_index())

In [27]:
top5_rf = rf_ranking.sort_values(by="XG_Pred",ascending=False).head(10)

print(top5_rf)

          IL NAME   XG_Pred
68    [TETAH][Pz]  2.049091
67    [TETAH][Py]  1.701037
66    [TETAH][Im]  1.694576
1     [AmemI][Br]  1.677461
69    [TETAH][Tz]  1.520531
57  [P66614][Gly]  1.265872
56  [P66614][Ala]  1.075536
71  [aP4443][Ala]  0.982325
58  [P66614][Ile]  0.961553
62  [P66614][Sar]  0.918744

In [5]:
X_train=pd.read_csv("../data/X_rf_trainpKa.csv")
X_test=pd.read_csv("../data/X_rf_testpKa.csv")
y_train=pd.read_csv("../data/y_trainpKa.csv")
y_test=pd.read_csv("../data/y_testpKa.csv")
y_train=y_train.squeeze()
y_test=y_test.squeeze()
model = xgb.XGBRegressor(objective='reg:squarederror',n_estimators=100, random_state=42)
model.fit(X_train,y_train)
y_train_pred=model.predict(X_train)
y_pred=model.predict(X_test)
from sklearn.metrics import(r2_score,mean_absolute_error,mean_squared_error)
r2=r2_score(y_test,y_pred)
mae = mean_absolute_error(y_test,y_pred)
rmse = np.sqrt(mean_squared_error(y_test,y_pred))
train_r2 = r2_score(y_train,y_train_pred)
print("Train R2:", round(train_r2,4))
print("TEST METRICS ARE")
print("R2 :", round(r2,4))
print("MAE :", round(mae,4))
print("RMSE :", round(rmse,4))

Train R2: 0.999
TEST METRICS ARE
R2 : 0.9788
MAE : 0.0307
RMSE : 0.0835

In [4]:
from sklearn.model_selection import cross_val_score
cv_scores = cross_val_score(model,X_train,y_train,cv=10,scoring="r2",n_jobs=-1)
print("Fold Scores:")
print(cv_scores)
print()
print("Mean CV R2:",round(cv_scores.mean(),4))
print("Std CV R2:",round(cv_scores.std(),4))

Fold Scores:
[0.98131917 0.96981636 0.98618047 0.98438231 0.97140248 0.96652447
 0.97536731 0.98066268 0.98576521 0.98348991]

Mean CV R2: 0.9785
Std CV R2: 0.0068